// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC649MK9PAOQj1qOgOGXOxg_ZzT5zw6Pdc',
    appId: '1:889424412911:web:5b525e7aadc60ded71db1a',
    messagingSenderId: '889424412911',
    projectId: 'firstflutterapp-a5c3f',
    authDomain: 'firstflutterapp-a5c3f.firebaseapp.com',
    storageBucket: 'firstflutterapp-a5c3f.appspot.com',
    measurementId: 'G-NNT861VJ5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7ihG_mRWlIzzBzjPcdJBx-q_cQ-AYtA',
    appId: '1:889424412911:android:cdde90461ad28f6771db1a',
    messagingSenderId: '889424412911',
    projectId: 'firstflutterapp-a5c3f',
    storageBucket: 'firstflutterapp-a5c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbla7NJq_1nXhxeSKkwim5ak1yqoJPPW0',
    appId: '1:889424412911:ios:e88751db4e89296871db1a',
    messagingSenderId: '889424412911',
    projectId: 'firstflutterapp-a5c3f',
    storageBucket: 'firstflutterapp-a5c3f.appspot.com',
    iosBundleId: 'com.emar.firstflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC649MK9PAOQj1qOgOGXOxg_ZzT5zw6Pdc',
    appId: '1:889424412911:web:15b956b69a6c744471db1a',
    messagingSenderId: '889424412911',
    projectId: 'firstflutterapp-a5c3f',
    authDomain: 'firstflutterapp-a5c3f.firebaseapp.com',
    storageBucket: 'firstflutterapp-a5c3f.appspot.com',
    measurementId: 'G-FK2RYRPX6Y',
  );
}
